# Generated by Django 3.1.3 on 2023-04-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230413_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ManyToManyField(to='onlinecourse.Lesson'),
        ),
    ]
